#!/usr/bin/env bash
# ceph-lab — gen_slos.sh
#
# Renders Sloth's PrometheusServiceLevel CRs into a single PrometheusRule CR
# (applications/infrastructure/sloth/prometheusrule.yaml) that the Prometheus
# Operator actually watches (kube-prometheus-stack's Prometheus CR sets
# ruleSelectorNilUsesHelmValues: false, so it picks up every PrometheusRule
# cluster-wide regardless of labels). Sloth's own `sloth generate` emits one
# PrometheusRule document per SLO, and recording/alerting runs both reuse the
# same metadata.name per SLO — applying either set standalone as separate
# per-SLO objects would collide, so this script merges every document's
# spec.groups into one combined CR instead.
#
# Run this after editing applications/infrastructure/sloth/prometheusservicelevels.yaml,
# then commit the diff.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SLO_SPEC="$REPO_ROOT/applications/infrastructure/sloth/prometheusservicelevels.yaml"
OUT_FILE="$REPO_ROOT/applications/infrastructure/sloth/prometheusrule.yaml"

command -v sloth >/dev/null 2>&1 || { echo "gen_slos.sh: 'sloth' CLI required (brew install sloth-cli)" >&2; exit 1; }
command -v yq >/dev/null 2>&1 || { echo "gen_slos.sh: 'yq' CLI required (brew install yq)" >&2; exit 1; }

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

sloth generate -i "$SLO_SPEC" --disable-alerts --no-color -o "$tmpdir/recording.k8s.yaml"
sloth generate -i "$SLO_SPEC" --disable-recordings --no-color -o "$tmpdir/alerting.k8s.yaml"

# Merge every SLO's .spec.groups (both the recording-only and alerting-only
# runs, across all SLOs) into one flat list, in source order.
yq eval-all '[.spec.groups[]] as $g ireduce ([]; . + $g) | {"groups": .}' \
    "$tmpdir/recording.k8s.yaml" "$tmpdir/alerting.k8s.yaml" > "$tmpdir/groups.yml"

{
    echo "# Code generated by gen_slos.sh — DO NOT EDIT BY HAND."
    echo "# Source: applications/infrastructure/sloth/prometheusservicelevels.yaml"
    echo "# Regenerate: just gen-slos"
    echo "apiVersion: monitoring.coreos.com/v1"
    echo "kind: PrometheusRule"
    echo "metadata:"
    echo "  name: sloth-generated-rules"
    echo "  namespace: monitoring"
    echo "  labels:"
    echo "    app.kubernetes.io/component: SLO"
    echo "    app.kubernetes.io/managed-by: sloth"
    echo "spec:"
    sed 's/^/  /' "$tmpdir/groups.yml"
} > "$OUT_FILE"

echo "gen_slos.sh: regenerated $OUT_FILE"
